### ISSUE TITLE
Unable to download imagery

### ISSUE THREAD

**Issue by HornerL** [SatelliteShorelines/CoastSeg#278] opened 2024-10-03 19:02 UTC
Please let me know if I should submit this issue as a Question rather than a Bug Report:

## Describe the bug

When using "SDS_coastsat_classifier.ipynb", the following issues:

First: I am unable to download imagery. When I "preview imagery" it shows that imagery is available for my timeframe and ROI, but when I select "Download Imagery" there are no image files in the data folder and the download report says "failed w/ error: ValueError".

Second: When I try to "Load Feature from File" there is no file dialog window for me to select a file.

## ALL software version info
**Desktop (please complete the following information):**
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
 - Latest version of CoastSeg 
 - OS: Windows 11 Enterprise version 23H2
 - Browser: Firefox Version 130.0.1
 - Python 3.8.3
 - jupyter notebook 7.2.2

### **Additional context**
See attached zipped folder with log, download report, ROI, etc. I experienced the same issues regardless of where my ROI was located including the "Case Study 1" area in Santa Cruz. 
[Coastseg_Issue_stuff.zip](https://github.com/user-attachments/files/17248779/Coastseg_Issue_stuff.zip)

**Comment by 2320sharon** [comment] 2024-10-24 18:49
Hi @HornerL  thank you for reporting your issue. We found the cause of this bug and we are working on getting it fixed.

**Comment by 2320sharon** [comment] 2024-10-26 00:13
Hi @HornerL I just wanted to let you know this bug was fixed in coastseg 1.2.15, but I would recommend you install 1.2.16 since that contains some additional bug fixes. 

After you update your coastseg installation please run the commands below to verify the update worked and that the `coastsat-package` code that was causing the issue has been updated to version 



In your coastseg environment can you run the commands below so we can verify you have the correct coastseg version installed `0.1.74`:

```
conda list coastseg

conda list conda list coastsat-package
```


These commands should return:
```
(coastseg) C:\development\coastseg_user_copy\CoastSeg>conda list coastseg
# packages in environment at C:\Users\sf230\anaconda3\envs\coastseg:
#
# Name                    Version                   Build  Channel
coastseg                  1.2.16                  pypi_0    pypi
```


```
(coastseg) C:\development\coastseg_user_copy\CoastSeg>conda list coastsat-package
# packages in environment at C:\Users\sf230\anaconda3\envs\coastseg:
#
# Name                    Version                   Build  Channel
coastsat-package          0.1.74                   pypi_0    pypi
```

I just released coastseg 1.2.16 so the conda package may not be released yet depending on when you see this. If its not out just wait and I'll release it before Monday.

**Comment by HornerL** [comment] 2024-10-28 22:38
Thank you Sharon. Has the conda package been released yet? I ran "conda
update coastseg " and "conda list coastseg " and it's showing version
1.2.14.

**Comment by HornerL** [comment] 2024-10-29 21:44
Everything seems to be working properly now. Thanks again

**Comment by 2320sharon** [comment] 2024-10-29 22:32
Hi @HornerL ,
I just saw your message, that version of coastseg is out on conda forge you can see it at https://anaconda.org/conda-forge/coastseg.

Glad that everything is working now. 👍

**Closed** 2024-10-31 16:16 UTC
