### ISSUE TITLE
Installation issue - Chris Sherwood

### ISSUE THREAD

**Issue by csherwood-usgs** [SatelliteShorelines/CoastSeg#266] opened 2024-07-03 14:34 UTC
Switching discussion of my installation issues from email to here.

I removed my anaconda installation and did a clean install of miniconda. I have built two different environments, and it looks like everything is working. I did a new build of the coastseg env, but I am getting the same error in cell one of `SDS_coastsat_classifier`.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from coastseg.common import initialize_gee
      2 # if you get an error here, enter your project id
      3 initialize_gee(auth_mode = "notebook",project='ee-christopherrobertsonsherwo')

ImportError: cannot import name 'initialize_gee' from 'coastseg.common' (C:\Users\csherwood\AppData\Roaming\Python\Python310\site-packages\coastseg\common.py)
```

**Comment by 2320sharon** [comment] 2024-07-03 16:12
Hi @csherwood-usgs 
Thanks for moving this over to GitHub I appreciate it!
Can you run :

```
conda list coastseg 
conda list python
```
this should let me know what version of coastseg and python you have. Very old versions of coastseg did not have the `initialize_gee` and I'm wondering if that's the cause of this error.

![image](https://github.com/SatelliteShorelines/CoastSeg/assets/61564689/61cb1627-a9bc-4643-9d2b-d3485452c516)

I also find it strange that the error message shows that the coastseg you have running in Python and not in your conda environment `(C:\Users\csherwood\AppData\Roaming\Python\Python310\site-packages\coastseg\common.py)`. As you can see in my screenshot below were I intentally imported the wrong module `initialize_gee1` it shows that the notebook was running using my `coastseg_11` (this is just what I named my coastseg environment ) conda environment `C:\Users\sf230\anaconda3\envs\coastseg_11\Lib\site-packages\coastseg\common.py](file:///C:/Users/sf230/anaconda3/envs/coastseg_11/Lib/site-packages/coastseg/common.py` It should have showed something like `C:\Users\csherwood\anaconda3\envs\coastseg\Lib\site-packages\coastseg\common.py`. I think you notebook is running using the wrong environment.

![image](https://github.com/SatelliteShorelines/CoastSeg/assets/61564689/3124c269-e868-497a-bce7-b999b1c94fd7)

**Comment by csherwood-usgs** [comment] 2024-07-03 16:18
Here is what I have. My coastset env was built today, so maybe the version on conda-forge is older? Also, I no longer have Anaconda and just installed miniforge, and I accepted the default locations for the install.

```(coastseg) D:\crs\src>conda list coastseg
# packages in environment at C:\Users\csherwood\AppData\Local\miniforge3\envs\coastseg:
#
# Name                    Version                   Build  Channel
coastseg                  1.2.9              pyhd8ed1ab_0    conda-forge

(coastseg) D:\crs\src>conda list python
# packages in environment at C:\Users\csherwood\AppData\Local\miniforge3\envs\coastseg:
#
# Name                    Version                   Build  Channel
brotli-python             1.1.0           py310h00ffb61_1    conda-forge
google-api-python-client  2.136.0            pyhd8ed1ab_0    conda-forge
ipython                   8.26.0             pyh7428d3b_0    conda-forge
python                    3.10.14         h4de0772_0_cpython    conda-forge
python-box                7.2.0           py310ha8f682b_0    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-duckdb             1.0.0           py310h9e98ed7_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge```

**Comment by 2320sharon** [comment] 2024-07-03 16:20
Thanks for getting back to me so fast. Your environment looks great! I think I see the issue though your notebook is not running coastseg using the coastseg package in `C:\Users\csherwood\AppData\Local\miniforge3\envs\coastseg` but using the coastseg installed in `C:\Users\csherwood\AppData\Roaming\Python\Python310\site-packages\coastseg`

**Comment by csherwood-usgs** [comment] 2024-07-03 16:23
How can that happen? I should not even have an environment there.

**Comment by csherwood-usgs** [comment] 2024-07-03 16:28
OK...full disclosure...as I was cleaning out my Anaconda distro, I deleted some the Continuum folder, not realizing that was where miniconda resided. Then my Win10 system did not allow me to remove miniconda. That ..\Python310\site-packages folder is full of stuff installed last August. But why does my jupyter lab point there?

**Comment by 2320sharon** [comment] 2024-07-03 18:34
I assuming you launched the jupyter notebook within your coastseg environment from the console, which should have open jupyter notebook with the correct kernel with the coastseg environment loaded. 

![image](https://github.com/SatelliteShorelines/CoastSeg/assets/61564689/0057c9d8-06c4-4363-94c2-f5c9f6631afe)

If that didn't work however, then it means we need to create a kernel for your coastseg environment. Run the commands below to create a jupyter notebook kernel for your current coastseg environment & upgrade it. Then after you've run that command run `jupyter lab SDS_coastsat_classifier.ipynb`.

```
conda activate coastseg
conda install -c conda-forge coastseg=1.2.10
python -m ipykernel install --user --name coastseg --display-name "Python (coastseg)"
```
Once you've created the kernel and launched the notebook you will need to launch the new kernel by following the steps in this gif. Hopefully this should allow you to load the up to date version of coastseg

![load_ipykernel](https://github.com/SatelliteShorelines/CoastSeg/assets/61564689/7774c35b-5bc1-4d0b-8deb-fc4abc42e47d)

**Comment by csherwood-usgs** [comment] 2024-07-03 19:43
The kernel approach didn't work...same error...I think there must be something wrong with my overall installation. I am not sure why all of that env stuff is still there, or what is making my jupyter lab point to it. I will work to remove some more stuff and re-install things if I break stuff.

**Comment by csherwood-usgs** [comment] 2024-07-03 20:00
Success (partially). I deleted some paths to the Continuum folders, and completely zapped the folders in ```Local\miniforge3\envs\coastseg```.

Now that cell is running and trying to connect me to GEE. But I have a new problem....I think I will need a screen share to trouble shoot this. I will try to chat with you.

**Closed** 2024-07-03 20:13 UTC
